###
POST http://localhost:7000/register
Content-Type: application/json

{
      "username": "rahul",
      "password":"rahul@2021",
      "name": "Ganesh",
      "email": "ganireddy651@gmail.com"
}
###


POST http://localhost:7000/login
Content-Type: application/json


{
      "username": "swetha",
      "password":"swetha@2000"
}
###
GET http://localhost:7000/users
###


GET http://localhost:7000/products
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN3ZXRoYSIsImlhdCI6MTY5NzcxMTkzN30.rWG-ndx1108p90wpdeXMBV7HSIWmwWMvKWRPQ6qmuPY
# ?sort_by="price"&category=""&title_search=""&rating=""